//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldDataClient.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WorldServiceSoap")]
    public interface WorldServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCountryByCode(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCountryByCodeAsync(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCityByName(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCityByNameAsync(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountryCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCitiesByCountryCode(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountryCode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCitiesByCountryCodeAsync(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByRegion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCountriesByRegion(string region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCountriesByRegionAsync(string region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPopulationByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetPopulationByCountry(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPopulationByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetPopulationByCountryAsync(string countryCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorldServiceSoapChannel : WorldDataClient.ServiceReference1.WorldServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldServiceSoapClient : System.ServiceModel.ClientBase<WorldDataClient.ServiceReference1.WorldServiceSoap>, WorldDataClient.ServiceReference1.WorldServiceSoap {
        
        public WorldServiceSoapClient() {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllCountries() {
            return base.Channel.GetAllCountries();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllCountriesAsync() {
            return base.Channel.GetAllCountriesAsync();
        }
        
        public System.Data.DataTable GetCountryByCode(string countryCode) {
            return base.Channel.GetCountryByCode(countryCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCountryByCodeAsync(string countryCode) {
            return base.Channel.GetCountryByCodeAsync(countryCode);
        }
        
        public System.Data.DataTable GetCityByName(string cityName) {
            return base.Channel.GetCityByName(cityName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCityByNameAsync(string cityName) {
            return base.Channel.GetCityByNameAsync(cityName);
        }
        
        public System.Data.DataTable GetCitiesByCountryCode(string countryCode) {
            return base.Channel.GetCitiesByCountryCode(countryCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCitiesByCountryCodeAsync(string countryCode) {
            return base.Channel.GetCitiesByCountryCodeAsync(countryCode);
        }
        
        public System.Data.DataTable GetCountriesByRegion(string region) {
            return base.Channel.GetCountriesByRegion(region);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCountriesByRegionAsync(string region) {
            return base.Channel.GetCountriesByRegionAsync(region);
        }
        
        public int GetPopulationByCountry(string countryCode) {
            return base.Channel.GetPopulationByCountry(countryCode);
        }
        
        public System.Threading.Tasks.Task<int> GetPopulationByCountryAsync(string countryCode) {
            return base.Channel.GetPopulationByCountryAsync(countryCode);
        }
    }
}
